# Generated by Django 6.0.4 on 2026-04-26 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('criteria_json', models.JSONField(help_text='Logic for unlocking this badge')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='HTML or Markdown content')),
                ('category', models.CharField(choices=[('forensics', 'Forensics'), ('web', 'Web'), ('reversing', 'Reversing'), ('crypto', 'Cryptography'), ('pwn', 'Pwn'), ('misc', 'Miscellaneous')], max_length=20)),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('flag_hash', models.CharField(max_length=128)),
                ('flag_case_sensitive', models.BooleanField(default=True)),
                ('flag_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.IntegerField(default=100)),
                ('dynamic_scoring', models.BooleanField(default=False)),
                ('hints', models.JSONField(blank=True, default=list, help_text='[{"text": "...", "cost_points": 0}, ...]')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of URLs to files')),
                ('external_resource_url', models.URLField(blank=True, help_text='Genially/Google Sites URL', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('time_limit_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('badges', models.ManyToManyField(blank=True, related_name='earners', to='challenges.badge')),
                ('solved_challenges', models.ManyToManyField(blank=True, related_name='solvers', to='challenges.challenge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ctf_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_submitted', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.IntegerField(default=0)),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solved_at'],
            },
        ),
    ]
