# Generated by Django 6.0.4 on 2026-04-26 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='criteria_json',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='badges',
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('skill', 'Habilidad'), ('achievement', 'Logro'), ('competitive', 'Competitiva'), ('secret', 'Secreta')], default='achievement', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='JSON flexible: {"type": "solve_count", "category": "web", "count": 5}'),
        ),
        migrations.AddField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='level',
            field=models.IntegerField(choices=[(1, 'Bronce'), (2, 'Plata'), (3, 'Oro'), (4, 'Platino')], default=1),
        ),
        migrations.AddField(
            model_name='badge',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badge',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='challenges.badge'),
        ),
        migrations.AddField(
            model_name='badge',
            name='rarity',
            field=models.CharField(choices=[('common', 'Común'), ('rare', 'Rara'), ('epic', 'Épica'), ('legendary', 'Legendaria')], default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Ej: web, crypto, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='challenges.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
