# Generated by Django 6.0.4 on 2026-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_remove_badge_criteria_json_remove_badge_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
